server:
  port: 8000
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/youlai?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 540000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:8761/eureka/
  instance:
    ip-address: localhost
    hostname: ${eureka.instance.ip-address} # eureka服务显示服务的host
    instance-id: 服务中心-8000
    prefer-ip-address: false # true为自动获取本地IPV4地址
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

oss:
  minio:
    endpoint: http://101.37.69.49:9000/
    access-key: minioadmin
    secret-key: minioadmin
auth:
  token:
    endpoint: http://localhost:8000/oauth/token

management:
  endpoints:
    web:
      exposure:
        include: "*"
